import { useCallback, useEffect, useRef, useState } from 'react';
import { Animated, Image, Platform, ScrollView, StatusBar, StyleSheet, View, useColorScheme } from 'react-native';
import { isDynamicThemeSupported, useMaterial3Theme } from '@pchmn/expo-material3-theme';
import { Appbar, BottomNavigation, Button, Card, Checkbox, Dialog, Divider, FAB, IconButton, List, MD3DarkTheme, MD3LightTheme, Menu, PaperProvider, Portal, ProgressBar, Snackbar, Switch, Text, TextInput, useTheme } from 'react-native-paper';
import { packNovels } from './src/core/packer';
import { exportAll, pickFolder, safeName, writeFilesToFolder } from './src/platform/exporter';
import { readCrashLog, saveEpub } from './src/platform/exportEpub';
import MaterialCommunityIcons from './src/platform/icons';
import { SafeAreaProvider, useSafeAreaInsets } from './src/platform/safeArea';
import type { Catalog, Progress } from './src/core/types';
import { sourceFor } from './src/sources';
import { readJson, writeJson } from './src/storage';

type ThemeMode = 'system' | 'light' | 'dark';
type ThemeColor = 'dynamic' | 'purple' | 'blue' | 'green' | 'orange';
type HistoryTask = { id: string; title: string; author: string; coverUrl?: string; type: 'EPUB'; sizeMb: number; wordsK: number; status: string; progress: number; detail: string; bytesBase64?: string };
const routes = [{ key: 'extract', title: '提取', focusedIcon: 'book-arrow-down', unfocusedIcon: 'book-arrow-down-outline' }, { key: 'tasks', title: '任务', focusedIcon: 'progress-download', unfocusedIcon: 'progress-download' }, { key: 'settings', title: '设置', focusedIcon: 'cog', unfocusedIcon: 'cog-outline' }];
const seeds: Record<Exclude<ThemeColor, 'dynamic'>, { label: string; color: string }> = { purple: { label: 'Material Purple', color: '#6750A4' }, blue: { label: 'Material Blue', color: '#0061A4' }, green: { label: 'Material Green', color: '#386A20' }, orange: { label: 'Material Orange', color: '#8C4A00' } };
const toBase64 = (data: Uint8Array) => { let result = ''; data.forEach(byte => { result += String.fromCharCode(byte); }); return btoa(result); };

function Scene({ children }: { children: React.ReactNode }) {
  const opacity = useRef(new Animated.Value(0)).current;
  useEffect(() => { Animated.timing(opacity, { toValue: 1, duration: 180, useNativeDriver: true }).start(); }, [opacity]);
  return <Animated.View style={[styles.scene, { opacity }]}>{children}</Animated.View>;
}

function AppContent() {
  const [tab, setTab] = useState(0); const [url, setUrl] = useState(''); const [catalog, setCatalog] = useState<Catalog>(); const [selected, setSelected] = useState<Set<number>>(new Set()); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState<Progress>(); const [message, setMessage] = useState(''); const [history, setHistory] = useState<HistoryTask[]>([]); const [fetchDialog, setFetchDialog] = useState(false);
  const [themeMode, setThemeMode] = useState<ThemeMode>('system'); const [themeColor, setThemeColor] = useState<ThemeColor>(Platform.OS === 'android' ? 'dynamic' : 'purple'); const [combine, setCombine] = useState(true); const [chapterTitle, setChapterTitle] = useState(true);
  const systemDark = useColorScheme() === 'dark'; const resolvedDark = themeMode === 'system' ? systemDark : themeMode === 'dark'; const insets = useSafeAreaInsets();
  const { theme: materialTheme, resetTheme, updateTheme } = useMaterial3Theme({ fallbackSourceColor: purpleColor(themeColor), sourceColor: purpleColor(themeColor) });
  const themeRef = useRef({ resetTheme, updateTheme }); themeRef.current = { resetTheme, updateTheme };
  const applyColor = useCallback(() => { try { if (themeColor === 'dynamic' && Platform.OS === 'android' && isDynamicThemeSupported) themeRef.current.resetTheme(); else if (themeColor !== 'dynamic') themeRef.current.updateTheme(seeds[themeColor].color); } catch { /* 动态取色原生模块不可用时保留纯 JS 回退主题 */ } }, [themeColor]);
  useEffect(() => { applyColor(); }, [applyColor]); useEffect(() => { let active = true; Promise.all([readJson('history', [] as HistoryTask[]), readJson('themeMode', 'system' as ThemeMode), readJson('themeColor', (Platform.OS === 'android' ? 'dynamic' : 'purple') as ThemeColor), readJson('combineVolumes', true), readJson('chapterTitle', true)]).then(([savedHistory, savedMode, savedColor, savedCombine, savedTitle]) => { if (!active) return; setHistory(savedHistory); setThemeMode(savedMode); setThemeColor(savedColor); setCombine(savedCombine); setChapterTitle(savedTitle); }); return () => { active = false; }; }, []); useEffect(() => { writeJson('history', history).catch(() => undefined); }, [history]); useEffect(() => { writeJson('themeMode', themeMode).catch(() => undefined); }, [themeMode]); useEffect(() => { writeJson('themeColor', themeColor).catch(() => undefined); }, [themeColor]); useEffect(() => { writeJson('combineVolumes', combine).catch(() => undefined); }, [combine]); useEffect(() => { writeJson('chapterTitle', chapterTitle).catch(() => undefined); }, [chapterTitle]);
  const base = resolvedDark ? MD3DarkTheme : MD3LightTheme; const theme = { ...base, colors: themeColor === 'dynamic' && Platform.OS === 'android' ? materialTheme[resolvedDark ? 'dark' : 'light'] : base.colors };
  const load = async () => { try { setBusy(true); setFetchDialog(true); const source = sourceFor(url.trim()); const novel = await source.getNovel(url.trim()); const next = await source.getCatalog(novel); setCatalog(next); setSelected(new Set(next.volumes.map((_, index) => index))); setMessage('目录已读取'); } catch (error) { setMessage(error instanceof Error ? error.message : '读取失败'); } finally { setBusy(false); setFetchDialog(false); } };
  const exportTask = async (task: HistoryTask) => { if (!task.bytesBase64) { setMessage('该任务没有可导出的 EPUB 数据'); return; } try { await saveEpub(`${task.title}.epub`, decodeBase64(task.bytesBase64)); setMessage('EPUB 已导出'); } catch (error) { setMessage(error instanceof Error ? error.message : '导出失败'); } };
  const exportFiles = history.filter(task => task.status === '已完成' && task.bytesBase64).map(task => ({ name: `${safeName(task.title)}.epub`, base64: task.bytesBase64 as string }));
  const [exportOpen, setExportOpen] = useState(false); const [exportFolder, setExportFolder] = useState('');
  const exportAllFiles = async () => { if (!exportFiles.length) { setMessage('没有可导出的文件'); return; } if (Platform.OS === 'windows') { setExportOpen(true); return; } try { const result = await exportAll(exportFiles); setMessage(result.cancelled ? '已取消导出' : `已导出 ${result.count} 个文件`); } catch (error) { setMessage(error instanceof Error ? error.message : '导出失败'); } };
  const browseFolder = async () => { try { const folder = await pickFolder(); if (folder) setExportFolder(folder); } catch (error) { setMessage(error instanceof Error ? error.message : '选择文件夹失败'); } };
  const confirmExportWindows = async () => { const folder = exportFolder.trim(); if (!folder) { setMessage('请先选择导出文件夹'); return; } try { const count = await writeFilesToFolder(exportFiles, folder); setExportOpen(false); setMessage(`已导出 ${count} 个文件`); } catch (error) { setMessage(error instanceof Error ? error.message : '导出失败'); } };
  const [crashLog, setCrashLog] = useState(''); const [crashLogOpen, setCrashLogOpen] = useState(false);
  const openCrashLog = async () => { setCrashLog(await readCrashLog() || '暂无崩溃日志'); setCrashLogOpen(true); };
  const build = async () => { if (!catalog || !selected.size) return; const id = `${Date.now()}`; const initial: HistoryTask = { id, title: catalog.novel.title, author: catalog.novel.author, coverUrl: catalog.novel.coverUrl, type: 'EPUB', sizeMb: 0, wordsK: Math.max(1, Math.round(selectedVolumes(catalog, selected).reduce((sum, volume) => sum + volume.chapters.length, 0) * 3.2)), status: '处理中', progress: 0, detail: '正在下载章节' }; const activeCatalog = catalog; const activeSelected = selected; setCatalog(undefined); setSelected(new Set()); setHistory(current => [initial, ...current.filter(task => task.title !== initial.title)]); setBusy(true); setTab(1); try { const files = await packNovels(sourceFor(activeCatalog.novel.url), activeCatalog, { combineVolumes: combine, addChapterTitle: chapterTitle, volumes: selectedVolumes(activeCatalog, activeSelected) }, value => { setProgress(value); setHistory(current => current.map(task => task.id === id ? { ...task, progress: value.total ? value.completed / value.total : 0, detail: value.label } : task)); }); const first = files[0]; setHistory(current => current.map(task => task.id === id ? { ...task, sizeMb: Number((first.bytes.byteLength / 1024 / 1024).toFixed(1)), bytesBase64: toBase64(first.bytes), status: '已完成', progress: 1, detail: `已生成 ${files.length} 个文件` } : task)); setMessage('EPUB 已生成，可在任务页点击导出'); } catch (error) { setHistory(current => current.map(task => task.id === id ? { ...task, status: '失败', detail: error instanceof Error ? error.message : '生成失败' } : task)); setMessage(error instanceof Error ? error.message : '生成失败'); } finally { setBusy(false); setProgress(undefined); } };
  const extract = <ExtractPage url={url} setUrl={setUrl} catalog={catalog} selected={selected} setSelected={setSelected} busy={busy} onRead={load} onBuild={build} history={history} progress={progress} />;
  const taskPage = <TaskPage tasks={history} progress={progress} onExport={exportTask} onExportAll={exportAllFiles} hasExportable={exportFiles.length > 0} />;
  const settings = <SettingsPage themeMode={themeMode} setThemeMode={setThemeMode} themeColor={themeColor} setThemeColor={setThemeColor} combine={combine} setCombine={setCombine} chapterTitle={chapterTitle} setChapterTitle={setChapterTitle} onReadCrashLog={openCrashLog} />;
  return <PaperProvider theme={theme} settings={{ icon: props => <MaterialCommunityIcons name={String(props.name) as never} color={props.color} size={props.size} /> }}><StatusBar translucent backgroundColor="transparent" animated barStyle={resolvedDark ? 'light-content' : 'dark-content'} /><View style={styles.page}><View style={[styles.appbarSlot, { paddingTop: insets.top, backgroundColor: theme.colors.surface }]}><Appbar.Header mode="small" statusBarHeight={0} style={styles.appbar}><Appbar.Content title={routes[tab].title} /></Appbar.Header></View><View style={styles.body}><BottomNavigation navigationState={{ index: tab, routes }} onIndexChange={setTab} renderScene={() => <Scene>{tab === 0 ? extract : tab === 1 ? taskPage : settings}</Scene>} sceneAnimationEnabled /></View></View><Portal><ProgressDialog visible={fetchDialog} /></Portal><Portal><ExportDialog visible={exportOpen} folder={exportFolder} onChangeFolder={setExportFolder} onBrowse={browseFolder} onConfirm={confirmExportWindows} onDismiss={() => setExportOpen(false)} /></Portal><Portal><Dialog visible={crashLogOpen} onDismiss={() => setCrashLogOpen(false)}><Dialog.Icon icon="file-alert" /><Dialog.Title>崩溃日志</Dialog.Title><Dialog.ScrollArea style={styles.crashLog}><Text selectable>{crashLog}</Text></Dialog.ScrollArea><Dialog.Actions><Button onPress={() => setCrashLogOpen(false)}>关闭</Button></Dialog.Actions></Dialog></Portal><Snackbar visible={Boolean(message)} onDismiss={() => setMessage('')} duration={3500}>{message}</Snackbar></PaperProvider>;
}

function ExtractPage({ url, setUrl, catalog, selected, setSelected, busy, onRead, onBuild, history, progress }: { url: string; setUrl: (value: string) => void; catalog?: Catalog; selected: Set<number>; setSelected: React.Dispatch<React.SetStateAction<Set<number>>>; busy: boolean; onRead: () => void; onBuild: () => void; history: HistoryTask[]; progress?: Progress }) {
  const [expanded, setExpanded] = useState(false); const pendingVolumes = catalog?.volumes ?? [];
  return <View style={styles.flex}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TextInput label="小说链接" value={url} onChangeText={setUrl} mode="outlined" autoCapitalize="none" autoCorrect={false} keyboardType="url" placeholder="粘贴小说链接" right={url ? <TextInput.Icon icon="close-circle" onPress={() => setUrl('')} /> : undefined} />{catalog && <Card mode="outlined" style={styles.selectionCard}><Card.Content style={styles.selectionContent}><View style={styles.rowBetween}><Text variant="titleMedium">任务</Text><IconButton icon={expanded ? 'chevron-up' : 'chevron-down'} onPress={() => setExpanded(value => !value)} /></View><ScrollView nestedScrollEnabled style={expanded ? styles.expandedList : styles.collapsedList}>{(expanded ? pendingVolumes : pendingVolumes.slice(0, 1)).map((volume, index) => <Card key={`${volume.title}-${index}`} mode="contained" style={styles.volumeCard} onPress={() => setSelected(current => { const next = new Set(current); next.has(index) ? next.delete(index) : next.add(index); return next; })}><Card.Content style={styles.volumeRow}><Checkbox status={selected.has(index) ? 'checked' : 'unchecked'} /><View style={styles.flex}><Text variant="titleMedium">{volume.title || catalog.novel.title}</Text><Text variant="bodySmall">{volume.chapters.length} 章</Text></View></Card.Content></Card>)}</ScrollView></Card.Content></Card>}{history.length > 0 && <View style={styles.taskPanel}>{history.slice(0, 3).map(task => <QueueCard key={task.id} task={task} />)}</View>}{progress && <ProgressBar progress={progress.total ? progress.completed / progress.total : 0} />}</ScrollView><FAB icon={catalog ? 'play' : 'book-arrow-down'} label={catalog ? '开始' : '提取'} style={styles.fab} disabled={busy || !url.trim() || Boolean(catalog && !selected.size)} onPress={catalog ? onBuild : onRead} /></View>;
}

function ProgressDialog({ visible }: { visible: boolean }) { return <Dialog visible={visible} dismissable={false}><Dialog.Icon icon="cloud-download-outline" /><Dialog.Title>正在获取数据</Dialog.Title><Dialog.Content><ProgressBar indeterminate /></Dialog.Content></Dialog>; }

function QueueCard({ task }: { task: HistoryTask }) { return <View style={styles.queueCard}><Cover uri={task.coverUrl} /><View style={styles.queueText}><Text variant="titleSmall" numberOfLines={1}>{task.title}</Text><Text variant="bodySmall" numberOfLines={1}>{task.author}</Text><ProgressBar progress={task.progress} style={styles.queueProgress} /></View><Text variant="labelMedium">{task.detail}</Text></View>; }
function TaskPage({ tasks, progress, onExport, onExportAll, hasExportable }: { tasks: HistoryTask[]; progress?: Progress; onExport: (task: HistoryTask) => void; onExportAll: () => void; hasExportable: boolean }) { return <View style={styles.flex}><ScrollView contentContainerStyle={styles.content}>{progress && <ProgressBar progress={progress.total ? progress.completed / progress.total : 0} />}{tasks.map(task => <HistoryCard key={task.id} task={task} onExport={onExport} />)}</ScrollView><FAB icon="folder-upload" label="导出" style={styles.fab} disabled={!hasExportable} onPress={onExportAll} /></View>; }
function ExportDialog({ visible, folder, onChangeFolder, onBrowse, onConfirm, onDismiss }: { visible: boolean; folder: string; onChangeFolder: (value: string) => void; onBrowse: () => void; onConfirm: () => void; onDismiss: () => void }) { return <Dialog visible={visible} onDismiss={onDismiss}><Dialog.Icon icon="folder-upload-outline" /><Dialog.Title>导出到文件夹</Dialog.Title><Dialog.Content><TextInput label="文件夹路径" value={folder} onChangeText={onChangeFolder} mode="outlined" autoCapitalize="none" autoCorrect={false} placeholder="例如 D:\\Novels" /></Dialog.Content><Dialog.Actions><Button onPress={onDismiss}>取消</Button><Button icon="folder-open" onPress={onBrowse}>选择路径</Button><Button mode="contained" onPress={onConfirm}>确认</Button></Dialog.Actions></Dialog>; }
function HistoryCard({ task, onExport }: { task: HistoryTask; onExport: (task: HistoryTask) => void }) { const theme = useTheme(); return <Card mode="outlined" style={styles.historyCard} onPress={() => task.status === '已完成' && onExport(task)}><Card.Content style={styles.historyContent}><Cover uri={task.coverUrl} large /><View style={styles.historyMiddle}><Text variant="titleMedium" numberOfLines={2}>{task.title}</Text><Text variant="bodyMedium" numberOfLines={1}>{task.author}</Text><Text variant="bodySmall">{task.status}</Text></View><View style={styles.statColumn}><Text variant="labelMedium" style={{ color: theme.colors.primary }}>{task.wordsK}k</Text><Text variant="labelMedium" style={{ color: theme.colors.primary }}>{task.type}</Text><Text variant="labelMedium" style={{ color: theme.colors.primary }}>{task.sizeMb} MB</Text></View></Card.Content></Card>; }
function Cover({ uri, large = false }: { uri?: string; large?: boolean }) { const theme = useTheme(); return uri ? <Image source={{ uri }} style={large ? styles.coverLarge : styles.cover} resizeMode="cover" /> : <View style={[large ? styles.coverLarge : styles.cover, styles.coverFallback, { backgroundColor: theme.colors.secondaryContainer }]}><MaterialCommunityIcons name="book-open-page-variant" size={large ? 30 : 22} color={theme.colors.onSecondaryContainer} /></View>; }
function SettingsPage({ themeMode, setThemeMode, themeColor, setThemeColor, combine, setCombine, chapterTitle, setChapterTitle, onReadCrashLog }: { themeMode: ThemeMode; setThemeMode: (value: ThemeMode) => void; themeColor: ThemeColor; setThemeColor: (value: ThemeColor) => void; combine: boolean; setCombine: (value: boolean) => void; chapterTitle: boolean; setChapterTitle: (value: boolean) => void; onReadCrashLog: () => void }) { return <ScrollView contentContainerStyle={styles.settings}><SettingMenu title="深色模式" value={modeLabel(themeMode)} options={[['system', '跟随系统'], ['dark', '深色'], ['light', '浅色']]} onSelect={value => setThemeMode(value as ThemeMode)} /><SettingMenu title="主题色" value={colorLabel(themeColor)} options={[['dynamic', '莫奈取色'], ...Object.entries(seeds).map(([key, value]) => [key, value.label] as [string, string])]} onSelect={value => setThemeColor(value as ThemeColor)} disabled={themeColor === 'dynamic' && Platform.OS !== 'android'} /><List.Item title="合并分卷" description="将选择的分卷写入一个 EPUB" right={() => <Switch value={combine} onValueChange={setCombine} />} /><List.Item title="添加章节标题" description="在章节正文开头显示标题" right={() => <Switch value={chapterTitle} onValueChange={setChapterTitle} />} /><List.Item title="查看崩溃日志" description="读取应用私有目录下的 crash.log" onPress={onReadCrashLog} right={props => <List.Icon {...props} icon="file-alert" />} /></ScrollView>; }
function SettingMenu({ title, value, options, onSelect, disabled = false }: { title: string; value: string; options: [string, string][]; onSelect: (value: string) => void; disabled?: boolean }) { const [open, setOpen] = useState(false); return <Menu visible={open} onDismiss={() => setOpen(false)} anchor={<List.Item title={title} description={disabled ? 'Android 12+ 可用' : value} onPress={() => setOpen(true)} right={props => <List.Icon {...props} icon="chevron-down" />} />}><Menu.Item title={title} disabled /><Divider />{options.map(([key, label]) => <Menu.Item key={key} title={label} leadingIcon={key === value ? 'check' : undefined} onPress={() => { onSelect(key); setOpen(false); }} />)}</Menu>; }
const selectedVolumes = (catalog: Catalog, selected: Set<number>) => catalog.volumes.filter((_, index) => selected.has(index));
const purpleColor = (color: ThemeColor) => color === 'dynamic' ? '#6750A4' : seeds[color].color;
const modeLabel = (mode: ThemeMode) => ({ system: '跟随系统', dark: '深色', light: '浅色' })[mode];
const colorLabel = (color: ThemeColor) => color === 'dynamic' ? '莫奈取色' : seeds[color].label;
function decodeBase64(value: string) { /* eslint-disable no-bitwise -- Base64 is a binary stream. */ const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'; const input = value.replace(/\s/g, '').replace(new RegExp('=+$'), ''); const bytes: number[] = []; let buffer = 0; let bits = 0; for (const char of input) { const digit = alphabet.indexOf(char); if (digit < 0) throw new Error('无效的 EPUB 数据'); buffer = (buffer << 6) | digit; bits += 6; if (bits >= 8) { bits -= 8; bytes.push((buffer >> bits) & 0xff); } } return Uint8Array.from(bytes); }
const styles = StyleSheet.create({ page: { flex: 1 }, body: { flex: 1 }, scene: { flex: 1 }, flex: { flex: 1 }, appbarSlot: { elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 3, zIndex: 2 }, appbar: { backgroundColor: 'transparent', height: 56 }, content: { gap: 16, padding: 20, paddingBottom: 110 }, settings: { paddingBottom: 32, paddingTop: 8 }, muted: { opacity: 0.7 }, rowBetween: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, taskPanel: { gap: 12 }, selectionCard: { marginTop: 4 }, selectionContent: { gap: 8 }, collapsedList: { maxHeight: 88 }, expandedList: { maxHeight: 270 }, queueCard: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 8 }, queueText: { flex: 1, gap: 3 }, queueProgress: { marginTop: 4 }, cover: { alignItems: 'center', borderRadius: 4, height: 56, justifyContent: 'center', width: 42 }, coverLarge: { alignItems: 'center', borderRadius: 4, height: 92, justifyContent: 'center', width: 70 }, coverFallback: { overflow: 'hidden' }, historyCard: { marginBottom: 12 }, historyContent: { alignItems: 'center', flexDirection: 'row', gap: 14, minHeight: 120 }, historyMiddle: { alignSelf: 'stretch', flex: 1, gap: 6, justifyContent: 'center' }, statColumn: { alignItems: 'flex-end', gap: 8, justifyContent: 'center', minWidth: 58 }, fab: { bottom: 18, position: 'absolute', right: 18 }, volumeCard: { marginBottom: 2 }, volumeRow: { alignItems: 'center', flexDirection: 'row', gap: 8 }, dialogProgress: { alignSelf: 'center' }, crashLog: { maxHeight: 320 } });

function App() {
  return <SafeAreaProvider><AppContent /></SafeAreaProvider>;
}

export default App;
